### ISSUE TITLE
Fichier index des sous-dossiers pas pris en compte par le menu de gauche

### ISSUE THREAD

**Issue by skymaiden** [mfrancois/alambic#1]
Si on crée un sous-dossier dans un projet son fichier index n'est pas utilisé pour le menu de gauche. L'index du sous-dossier est affiché dans le sous-menu en tant que "index".

**Comment by mfrancois** [comment]
Bug fixed on release 0.2.1

**Comment by skymaiden** [comment]
Tested the fix and it works great thanks!
